# Template file for a composite aciton

# Each composite action is created using a directory of it's name followed by an action.yaml file containing the metadata for it.
# The following template represents the basic structure for all actions

name: "Hello world..."
description: "Greet world"
# Inputs are passed using a "with" under the step where the action is called
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
runs:
  # This using is required for all composite actions
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
