# Template file for a composite aciton

# Each composite action is created using a directory of it's name followed by an action.yaml file containing the metadata for it.
# The following template represents the basic structure for all actions

name: "Hello someone..."
description: "Greet someone"
# Inputs are passed using a "with" under the step where the action is called
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  # This using is reequired for all composite actions
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
