# Template workflow for the intro-to-gha repository
name: Hello World

# This specifies triggers for the workflow
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
concurrency:
  # This is a fully-formed ref of the branch or tag that triggered the workflow run.
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # An example job
  lets-get-started:
    runs-on: ubuntu-latest
    steps:
      # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it. It's needed for every workflow
      - uses: actions/checkout@v3
        with:
          repository: ${{github.repository}}
      - name: Run a one-line script
        run: echo "This is an example"
      - name: Call my reusable action
        id: my-action
        uses: ./.github/actions/starter-action
        with:
          who-to-greet: "beebee"
      - name: Echo
        shell: bash
        run: |
          echo "Random number generated is ${{ steps.my-action.outputs.random-number }}"

  hello-world-plus-cool-variable:
    runs-on: ubuntu-latest
    outputs:
      random-number: ${{ steps.random-id.outputs.random-number }}
    steps:
      - uses: actions/checkout@v3
      - name: Harlow
        shell: bash
        run: |
          echo "harlow world <3"
      - name: Cool cool
        shell: bash
        run: |
          echo "${{ vars.COOL_VARIABLE }}"
      - name: Generate random number
        id: random-id
        shell: bash
        run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
  
  print-random-number:
    runs-on: ubuntu-latest
    needs: [hello-world-plus-cool-variable]
    steps:
      - uses: actions/checkout@v3
      - name: Echo random number
        shell: bash
        run: echo "${{ needs.hello-world-plus-cool-variable.outputs.random-number }}""