# Template workflow for the intro-to-gha repository
name: Hello World

# This specifies triggers for the workflow
on:
  pull_request:
    types: [opened, reopened, synchronize]
concurrency:
  # This is a fully-formed ref of the branch or tag that triggered the workflow run.
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # An example job
  lets-get-started:
    runs-on: ubuntu-latest
    steps:
      # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it. It's needed for every workflow
      - uses: actions/checkout@v3
        with:
          repository: ${{github.repository}}
      - name: Run a one-line script
        run: echo "This is an example"
      - name: Call my reusable action
        id: my-action
        uses: ./.github/actions/starter-action
        with:
          who-to-greet: "rashi"
      - name: Echo
        shell: bash
        run: |
          echo "Random number generated is ${{ steps.my-action.outputs.random-number }}"

  # Hello-world
  hello-world:
    runs-on: ubuntu-latest
    outputs:
      random-number: ${{ steps.random-number-step.outputs.random-number }}
    steps:
      - uses: actions/checkout@v3
      - name: Call hello world action
        uses: ./.github/actions/hello-world
      - name: Print cool variable
        shell: bash
        run: |
          echo "${{ vars.COOL_VARIABLE }}"
      - name: Generate random number
        id: random-number-step
        shell: bash
        run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT

  print-random-number:
    runs-on: ubuntu-latest
    needs: [hello-world]
    steps:
      - uses: actions/checkout@v3
      - name: Print random number
        shell: bash
        run: echo "${{needs.hello-world.outputs.random-number}}"

  calling-a-composite-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            This is a comment :smile:
