# Template workflow for the intro-to-gha repository
name: Hello World

# This specifies triggers for the workflow
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
concurrency:
  # This is a fully-formed ref of the branch or tag that triggered the workflow run.
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # An example job
  lets-get-started:
    runs-on: ubuntu-latest
    steps:
      # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it. It's needed for every workflow
      - uses: actions/checkout@v3
      - name: Run a one-line script
        uses: ./.github/actions/philip-action
      - name: Call my reusable action
        id: my-action
        uses: ./.github/actions/starter-action
        with:
          who-to-greet: "beebee"
      - name: Echo
        shell: bash
        run: |
          echo "Random number generated is ${{ steps.my-action.outputs.random-number }}"

  hello-world:
    runs-on: ubuntu-latest
    outputs:
      random-number: ${{ steps.random-id.outputs.random-number }}
    steps:
      - uses: actions/checkout@v3
      - name: hello world
        run: echo "hello world"
      - name: cool
        run: echo "${{ vars.COOL_VARIABLE }}"
      - name: generate random number
        id: random-id
        shell: bash
        run:  echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT

  print-random-number:
    runs-on: ubuntu-latest
    needs: [hello-world]
    steps:
      - uses: actions/checkout@v3
      - name: Echo number
        shell: bash
        run: echo "${{ needs.hello-world.outputs.random-number }}"
