# Template workflow for the intro-to-gha repository
name: Hello World

# This specifies triggers for the workflow
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
concurrency:
  # This is a fully-formed ref of the branch or tag that triggered the workflow run.
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # An example job
  lets-get-started:
    runs-on: ubuntu-latest
    steps:
      # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it. It's needed for every workflow
      - uses: actions/checkout@v3
        with:
          repository: ${{github.repository}}
      - name: Run a one-line script
        run: echo "This is an example"
      - name: Call my reusable action
        id: my-action
        uses: ./.github/actions/starter-action
        with:
          who-to-greet: "beebee"
      - name: Echo
        shell: bash
        run: |
          echo "Random number generated is ${{ steps.my-action.outputs.random-number }}"

  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo "Hello world"
